# Generated by Django 2.2.3 on 2019-11-24 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crudobject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crudcover', models.ImageField(blank=True, upload_to='crudcovers/')),
            ],
            options={
                'permissions': [('special_status', 'Can read all crudobjects')],
            },
        ),
        migrations.AddIndex(
            model_name='crudobject',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
