# Generated by Django 2.2.3 on 2019-11-26 00:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('crudobjects', '0004_auto_20191125_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudobject',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
